### ISSUE TITLE
It doesn't ping when I go over column 80

### ISSUE THREAD

**Issue by rbanffy** [rbanffy/selectric-mode#2]
Typewriters use to give an audio warning when you cross the right margin. It would be useful here.

**Comment by swflint** [comment]
Right margin is adjustable.  Not always 80 chars.  I might be able to get a recording of the ding from the same model, but you'll have to edit it.

**Comment by semente** [comment]
I guess you must use the value returned by `(current-fill-column)`.

By the way, I love this minor mode! :+1:
