### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by tecosaur** [rbanffy/selectric-mode#28]
Hi @rbanffy,

I recently started using this extension, and it's great fun! Few of the sounds didn't quite sound right, so I found this repo. Looking at the last commit, and open PRs I am wondering whether this is still maintained?

It would be great if you could even spare a few minutes to go through what's here and make this mode even better!

Thanks for your work,

tecosaur.

**Comment by rbanffy** [comment]
Sorry about that. I'll go over the issues and PRs and check what can be done.

**Comment by tecosaur** [comment]
All good :) It's just nice to see that you haven't lost interest / abandoned it :stuck_out_tongue_winking_eye:

**Comment by rbanffy** [comment]
Nevah!
