### ISSUE TITLE
Melpa recipe?

### ISSUE THREAD

**Issue by CestDiego** [rbanffy/selectric-mode#3]
Could you submit this to MELPA ? this looks awesome, otherwise I volunteer to do it for you with your consent :)

**Comment by rbanffy** [comment]
I have no idea how to submit it to MELPA, but if you want to help, I gladly accept.

**Comment by CestDiego** [comment]
^ done.

**Comment by CestDiego** [comment]
@rbanffy You should check out recomendations from @purcell here: https://github.com/milkypostman/melpa/pull/3345#issuecomment-160878147
